version: '3.7'

services:

  php-fpm:
    build: docker
    container_name: 'php'
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: itmo
      LC_ALL: C.UTF-8
    volumes:
      - mysql:/var/lib/mysql:delegated
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: 'phpmyadmin'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100000000
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge

volumes:
  mysql:
